server:
  port: 8080

spring:
  application:
    name: restaurant-service

  # --- CONFIGURACIÓN DE AURORA RDS (POSTGRESQL) ---
  datasource:
    # 🌟 CORREGIDO: Se cambió 'jdbc:restdb' por 'jdbc:postgresql'
    url: jdbc:postgresql://restdb.c43ky6u26e8h.us-east-1.rds.amazonaws.com:5432/postgres
    username: tortuga
    password: SPEAKINGMIND123*
    driver-class-name: org.postgresql.Driver

  # 🌟 CORREGIDO: 'jpa' ahora está perfectamente alineado dentro de 'spring'
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: ${JPA_DDL_AUTO:update}
    show-sql: false 
    properties:
      hibernate:
        format_sql: false

  # --- CONFIGURACIÓN DE AMAZON COGNITO ---
  # 🌟 CORREGIDO: 'security' ahora está alineado correctamente dentro de 'spring'
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${COGNITO_ISSUER_URI:https://cognito-idp.us-east-1.amazonaws.com/us-east-1_dVFfTH2gg}