worker_processes 1;

events {
    worker_connections 1024;
}

http {
    include mime.types;
    default_type application/octet-stream;

    sendfile on;
    keepalive_timeout 65;

    upstream restaurant_service {
        server restaurant-service:8080;
    }

    upstream client_preferences_service {
        server client-preferences-service:8082;
    }

    server {
        listen 80;
        server_name localhost;

        location /api/v1/preferences {
            proxy_pass http://client_preferences_service;
            include /etc/nginx/proxy_headers.conf;
        }

        location /api/v1/ {
            proxy_pass http://restaurant_service;
            include /etc/nginx/proxy_headers.conf;
        }
    }
}