server:
  port: 8080

spring:
  application:
    name: restaurant-service

  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: create
    show-sql: false
    properties:
      hibernate:
        format_sql: true
        generate_statistics: true

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${COGNITO_ISSUER_URI}

logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.orm.jdbc.bind: TRACE

cognito:
  user-pool-id: ${COGNITO_USER_POOL_ID}
  app-client-id: ${COGNITO_APP_CLIENT_ID}
  domain-base: ${COGNITO_DOMAIN_BASE}
  redirect-uri: ${COGNITO_REDIRECT_URI}

services:
  client-preferences:
    url: ${CLIENT_PREFERENCES_SERVICE_URL}